# syntax=docker/dockerfile:1
# Generated by DeepAgent. Rerunning the deploy regenerates this file — delete this line to keep your own edits.
# --- Build stage: install ALL deps (build tools live in devDependencies) ---
FROM node:20-bookworm-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm pkg delete scripts.prepare scripts.postinstall >/dev/null 2>&1 || true && if [ -f package-lock.json ]; then npm ci || npm ci --legacy-peer-deps; else npm install; fi
COPY . .
# The repo's own postinstall, now that the files it reads are here
# (no-op when the package.json defines none).
RUN npm run postinstall --if-present
# Build-time env for the frontend build (added by DeepAgent).
# These are framework-prefixed, i.e. inlined into the public bundle by
# design — never put a credential in a build arg. The empty defaults keep
# the image buildable with no --build-arg; CI overrides them with the
# real values.
ARG VITE_API_URL=""
ENV VITE_API_URL=${VITE_API_URL}
RUN npm run build

# --- Runtime: unprivileged nginx (already non-root uid 101, listens on 8080) ---
FROM nginxinc/nginx-unprivileged:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget -q --spider http://localhost:8080/healthz || exit 1
CMD ["nginx", "-g", "daemon off;"]
